//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelEnvAds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertises
    {
        public Advertises()
        {
            this.Images = new HashSet<Images>();
        }
    
        public long AdvertiseId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CampainId { get; set; }
        public Nullable<int> StructureId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> FarsiDateTimeIndex { get; set; }
        public Nullable<System.DateTime> EnDateTime { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public string FarsiDateString { get; set; }
        public Nullable<long> EndFarsiDateTimeIndex { get; set; }
        public Nullable<System.DateTime> EndEnDateTime { get; set; }
        public string TimeString { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Structures Structures { get; set; }
        public virtual ICollection<Images> Images { get; set; }
        public virtual Campains Campains { get; set; }
    }
}
