//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelEnvAds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.Advertises = new HashSet<Advertises>();
            this.Campains = new HashSet<Campains>();
            this.Competitors = new HashSet<Competitors>();
        }
    
        public int BrandId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BrandImageName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> PanelId { get; set; }
    
        public virtual ICollection<Advertises> Advertises { get; set; }
        public virtual ICollection<Campains> Campains { get; set; }
        public virtual ICollection<Competitors> Competitors { get; set; }
    }
}
