//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelEnvAds
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_EnvAdsEntities : DbContext
    {
        public DB_EnvAdsEntities()
            : base("name=DB_EnvAdsEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddressTypes> AddressTypes { get; set; }
        public DbSet<Advertises> Advertises { get; set; }
        public DbSet<Brands> Brands { get; set; }
        public DbSet<Campains> Campains { get; set; }
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Competitors> Competitors { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<Structures> Structures { get; set; }
        public DbSet<StructureTypes> StructureTypes { get; set; }
    }
}
