//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelEnvAds
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureTypes
    {
        public StructureTypes()
        {
            this.Structures = new HashSet<Structures>();
        }
    
        public int StructureTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Structures> Structures { get; set; }
    }
}
