//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNewMeda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RubikaEntities : DbContext
    {
        public DB_RubikaEntities()
            : base("name=DB_RubikaEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_News> Tbl_News { get; set; }
        public DbSet<Tbl_NewsGroups> Tbl_NewsGroups { get; set; }
        public DbSet<Tbl_Sites> Tbl_Sites { get; set; }
    }
}
