//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNewMeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sites
    {
        public Tbl_Sites()
        {
            this.Tbl_News = new HashSet<Tbl_News>();
        }
    
        public int SiteId { get; set; }
        public string SiteTitle { get; set; }
        public string SiteUrl { get; set; }
        public Nullable<int> SiteType { get; set; }
    
        public virtual ICollection<Tbl_News> Tbl_News { get; set; }
    }
}
