//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.Pages
{


    public partial class CompetitorsAnalyze
    {

        /// <summary>
        /// hddParmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hddParmin;

        /// <summary>
        /// UC_Roghaba_PR_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_AllData UC_Roghaba_PR_AllData;

        /// <summary>
        /// UC_Roghaba_PR_AllDataByMedia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_AllDataByMedia UC_Roghaba_PR_AllDataByMedia;

        /// <summary>
        /// UC_Roghaba_Ads_Radio_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Radio_AllData UC_Roghaba_Ads_Radio_AllData;

        /// <summary>
        /// UC_Roghaba_Ads_Video_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Video_AllData UC_Roghaba_Ads_Video_AllData;

        /// <summary>
        /// UC_Roghaba_Ads_RadioVideo_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_RadioVideo_AllData UC_Roghaba_Ads_RadioVideo_AllData;

        /// <summary>
        /// UC_Roghaba_Ads_Mohiti_Ekran control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Mohiti_Ekran UC_Roghaba_Ads_Mohiti_Ekran;

        /// <summary>
        /// UC_Roghaba_Ads_Mohiti_Makan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Mohiti_Makan UC_Roghaba_Ads_Mohiti_Makan;

        /// <summary>
        /// UC_Roghaba_Ads_Bilboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Bilboard UC_Roghaba_Ads_Bilboard;

        /// <summary>
        /// UC_Roghaba_Ads_AberPiade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_AberPiade UC_Roghaba_Ads_AberPiade;

        /// <summary>
        /// UC_Roghaba_Ads_EsteraBoard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_EsteraBoard UC_Roghaba_Ads_EsteraBoard;

        /// <summary>
        /// UC_Roghaba_Ads_LightBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_LightBox UC_Roghaba_Ads_LightBox;

        /// <summary>
        /// UC_Roghaba_Ads_Mohiti_Campain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_Mohiti_Campain UC_Roghaba_Ads_Mohiti_Campain;

        /// <summary>
        /// UC_Roghaba_Ads_OnlineBanner_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_OnlineBanner_AllData UC_Roghaba_Ads_OnlineBanner_AllData;

        /// <summary>
        /// UC_Roghaba_Ads_OnlineBanner_Safeyi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Ads_OnlineBanner_Safeyi UC_Roghaba_Ads_OnlineBanner_Safeyi;

        /// <summary>
        /// UC_Roghaba_PR_Instagram_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Instagram_Mohtava UC_Roghaba_PR_Instagram_Mohtava;

        /// <summary>
        /// UC_Roghaba_PR_Instagram_TopLike control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Instagram_TopLike UC_Roghaba_PR_Instagram_TopLike;

        /// <summary>
        /// UC_Roghaba_PR_Instagram_TopComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Instagram_TopComment UC_Roghaba_PR_Instagram_TopComment;

        /// <summary>
        /// UC_Roghaba_PR_Instagram_TopContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Instagram_TopContent UC_Roghaba_PR_Instagram_TopContent;

        /// <summary>
        /// UC_Roghaba_PR_Telegram_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Telegram_Mohtava UC_Roghaba_PR_Telegram_Mohtava;

        /// <summary>
        /// UC_Roghaba_PR_Telegram_TopView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Telegram_TopView UC_Roghaba_PR_Telegram_TopView;

        /// <summary>
        /// UC_Roghaba_PR_Telegram_TopChannel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Telegram_TopChannel UC_Roghaba_PR_Telegram_TopChannel;

        /// <summary>
        /// UC_Roghaba_PR_Telegram_TopContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Telegram_TopContent UC_Roghaba_PR_Telegram_TopContent;

        /// <summary>
        /// UC_Roghaba_PR_Twitter_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Twitter_Mohtava UC_Roghaba_PR_Twitter_Mohtava;

        /// <summary>
        /// UC_Roghaba_PR_Twitter_TopRetwitte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Twitter_TopRetwitte UC_Roghaba_PR_Twitter_TopRetwitte;

        /// <summary>
        /// UC_Roghaba_PR_Twitter_TopFavorite control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Twitter_TopFavorite UC_Roghaba_PR_Twitter_TopFavorite;

        /// <summary>
        /// UC_Roghaba_PR_Twitter_TopAllContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Twitter_TopAllContent UC_Roghaba_PR_Twitter_TopAllContent;

        /// <summary>
        /// UC_Roghaba_PR_Map_Location control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Map_Location UC_Roghaba_PR_Map_Location;

        /// <summary>
        /// UC_Roghaba_PR_Jensiat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Jensiat UC_Roghaba_PR_Jensiat;

        /// <summary>
        /// UC_Roghaba_PR_SocialMedia_Hashtag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_SocialMedia_Hashtag UC_Roghaba_PR_SocialMedia_Hashtag;

        /// <summary>
        /// UC_Roghaba_PR_Abri_ByMedia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_Abri_ByMedia UC_Roghaba_PR_Abri_ByMedia;

        /// <summary>
        /// UC_Roghaba_PR_News_BySource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_PR_News_BySource UC_Roghaba_PR_News_BySource;

        /// <summary>
        /// UC_Roghaba_Show_Ads_Video_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_Ads_Video_AllData UC_Roghaba_Show_Ads_Video_AllData;

        /// <summary>
        /// UC_Roghaba_Show_Ads_Radio_AllData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_Ads_Radio_AllData UC_Roghaba_Show_Ads_Radio_AllData;

        /// <summary>
        /// UC_Roghaba_Show_PR_Twitter_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_PR_Twitter_Mohtava UC_Roghaba_Show_PR_Twitter_Mohtava;

        /// <summary>
        /// UC_Roghaba_Show_PR_Telegram_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_PR_Telegram_Mohtava UC_Roghaba_Show_PR_Telegram_Mohtava;

        /// <summary>
        /// UC_Roghaba_Show_PR_Instagram_Mohtava control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_PR_Instagram_Mohtava UC_Roghaba_Show_PR_Instagram_Mohtava;

        /// <summary>
        /// UC_Roghaba_Show_PR_News_BySource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::P_Art.UserControls.UC_Roghaba_Show_PR_News_BySource UC_Roghaba_Show_PR_News_BySource;
    }
}
