//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignNewsView
    {
        public int NewsID { get; set; }
        public Nullable<int> ParminId { get; set; }
        public int SiteID { get; set; }
        public string NewsDate { get; set; }
        public string NewsTime { get; set; }
        public string NewsTitle { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string NewsLink { get; set; }
        public Nullable<long> NewsDateIndex { get; set; }
        public Nullable<int> KeywordId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<long> NewsLinkCRC { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> NewsType { get; set; }
        public Nullable<long> NewsTitleCRC { get; set; }
        public Nullable<bool> IsFeederNews { get; set; }
        public Nullable<int> NewsGroupOrder { get; set; }
        public string KeyIds { get; set; }
        public Nullable<byte> NewsTypeShow { get; set; }
        public Nullable<long> NewsDateTimeIndex { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<byte> NewsValue { get; set; }
        public string SiteTitle { get; set; }
        public Nullable<int> SiteType { get; set; }
        public string KeywordName { get; set; }
        public string GroupName { get; set; }
        public string Color { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<int> OrderItem { get; set; }
    }
}
