
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class NewMediaInfluencedNewsEconomyView
{

    public int NewsID { get; set; }

    public int SiteID { get; set; }

    public string NewsTitle { get; set; }

    public string NewsLead { get; set; }

    public string NewsBody { get; set; }

    public string NewsPicture { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string NewsLink { get; set; }

    public Nullable<long> NewsDateIndex { get; set; }

    public Nullable<int> KeywordId { get; set; }

    public Nullable<long> NewsLinkCRC { get; set; }

    public string KeyIds { get; set; }

    public Nullable<long> NewsDateTimeIndex { get; set; }

    public string SiteTitle { get; set; }

    public string KeywordName { get; set; }

    public Nullable<int> RelatedCount { get; set; }

}

}
