//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class RssKeywordsView
    {
        public int KeyId { get; set; }
        public string KeywordName { get; set; }
        public Nullable<int> PanelId { get; set; }
        public Nullable<bool> IsConfirmingKeyword { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Color { get; set; }
        public Nullable<int> OrderItem { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public string GroupName { get; set; }
    }
}
