//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ParminUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string UserGroup { get; set; }
        public Nullable<bool> Supervisor { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string LastSessionID { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
    }
}
