
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_MemberParminSites
{

    public long ID { get; set; }

    public Nullable<int> MemberID { get; set; }

    public Nullable<int> SiteID { get; set; }

    public Nullable<int> PanelID { get; set; }

    public Nullable<byte> MediaType { get; set; }

}

}
