//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TLPChannels
    {
        public int ChannelID { get; set; }
        public string ChannelTitle { get; set; }
        public Nullable<long> AccessHash { get; set; }
        public Nullable<bool> Broadcast { get; set; }
        public Nullable<long> Cunstructor { get; set; }
        public string Username { get; set; }
        public string LastUpdate { get; set; }
        public string PhoneNumber { get; set; }
    }
}
