//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MobieDevice
    {
        public int DeviceID { get; set; }
        public string ParminIDs { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string UUID { get; set; }
        public string GoogleRegisterID { get; set; }
        public Nullable<System.DateTime> LastConnect { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ModelVersion { get; set; }
        public string CordovaVersion { get; set; }
        public string PlatformVersion { get; set; }
        public string AppVersion { get; set; }
        public string OperationVersion { get; set; }
        public string AppleRegisterID { get; set; }
        public string IPAddress { get; set; }
        public string IPCity { get; set; }
        public Nullable<bool> RecieveNotification { get; set; }
        public string NewsKeywordsIds { get; set; }
    }
}
