
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_DataCenterNews
{

    public int NewsID { get; set; }

    public Nullable<int> SiteID { get; set; }

    public Nullable<int> ParminID { get; set; }

    public string NewsDate { get; set; }

    public string NewsTime { get; set; }

    public string NewsTitle { get; set; }

    public string NewsLead { get; set; }

    public string NewsBody { get; set; }

    public string NewsUrl { get; set; }

    public string NewsImageUrl { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> KeywordId { get; set; }

    public Nullable<int> GroupId { get; set; }

    public Nullable<int> SortOrder { get; set; }

    public Nullable<int> NewsType { get; set; }

    public Nullable<long> NewsDateTimeIndex { get; set; }

    public string KeyIds { get; set; }

    public int ArchiveByMemberID { get; set; }

    public Nullable<long> ArchiveDateTime { get; set; }

    public Nullable<bool> IsChanged { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> DeletedByMemberID { get; set; }

}

}
