//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rss
    {
        public int RssId { get; set; }
        public int SiteId { get; set; }
        public string CategoryName { get; set; }
        public string RssLink { get; set; }
        public string LastItemLink { get; set; }
        public Nullable<System.DateTime> LastCheck { get; set; }
    
        public virtual Tbl_Sites Tbl_Sites { get; set; }
    }
}
