//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rate
    {
        public int RateID { get; set; }
        public int MemberID { get; set; }
        public int AgenceID { get; set; }
        public int NewsID { get; set; }
        public Nullable<byte> Rate { get; set; }
    
        public virtual Tbl_AgenceMembers Tbl_AgenceMembers { get; set; }
        public virtual Tbl_Agences Tbl_Agences { get; set; }
    }
}
