//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inbox
    {
        public long InboxId { get; set; }
        public int MemberId { get; set; }
        public int PanelId { get; set; }
        public int MediaType { get; set; }
        public long MediaId { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
