//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserjobLogMsg
    {
        public int ID { get; set; }
        public int SenderUserID { get; set; }
        public int UserID { get; set; }
        public int UserJobLogID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string DateIndex { get; set; }
        public string Message { get; set; }
        public bool Active { get; set; }
    }
}
