//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Parmin
    {
        public Tbl_Parmin()
        {
            this.Tbl_InstagramKeywords = new HashSet<Tbl_InstagramKeywords>();
            this.Tbl_InstagramPosts = new HashSet<Tbl_InstagramPosts>();
            this.Tbl_Relation_Gallery = new HashSet<Tbl_Relation_Gallery>();
        }
    
        public int ParminID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.Guid> ParminGid { get; set; }
        public string AgName { get; set; }
        public string EnAgName { get; set; }
        public Nullable<int> PanelCategory { get; set; }
        public string Connectionstring { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> SmsUserId { get; set; }
        public string SmsUserPass { get; set; }
        public string SmsMobiles { get; set; }
        public Nullable<bool> SmsActive { get; set; }
        public string SmsFormat { get; set; }
        public string PanelType { get; set; }
        public Nullable<long> NewsCount { get; set; }
        public Nullable<long> UnreadNews { get; set; }
        public string Mail { get; set; }
        public string BultanId { get; set; }
        public string Description { get; set; }
        public string ExportGozideh { get; set; }
        public string ExportMashrooh { get; set; }
        public string AnalyzKeywords { get; set; }
        public string Sites { get; set; }
        public Nullable<int> MediaKitType { get; set; }
        public Nullable<int> MediaKitGroupRootID { get; set; }
        public Nullable<int> MediaKitGroupID { get; set; }
        public string Rivals { get; set; }
        public Nullable<bool> DefaultActiveNews { get; set; }
        public string DefaultPrice { get; set; }
        public Nullable<long> Interval { get; set; }
        public Nullable<bool> AutoSave { get; set; }
        public string ParminLogo { get; set; }
        public Nullable<bool> MobileAppAccess { get; set; }
        public string DBName { get; set; }
        public string ParminColor { get; set; }
        public string ProductName { get; set; }
        public Nullable<bool> IsMobileNotification { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TelegramChannel { get; set; }
        public string TelegramBootKey { get; set; }
        public Nullable<int> GolrangBrandCode { get; set; }
        public Nullable<int> GolrangKasboKarCode { get; set; }
        public Nullable<int> GolrangStandardCode { get; set; }
        public Nullable<int> GolrangStrategicCode { get; set; }
        public Nullable<int> GolrangBazarCode { get; set; }
        public Nullable<bool> hdParmin { get; set; }
        public Nullable<bool> GolrangVerified { get; set; }
        public string ParminNimtaCodes { get; set; }
        public Nullable<int> MaxNewsMinuteToCheck { get; set; }
        public Nullable<int> MaxMovieMinuteToCheck { get; set; }
        public string AceessIds { get; set; }
        public string TelegramChannel2 { get; set; }
        public string TelegramChannel3 { get; set; }
        public string SocialTelegramChannel { get; set; }
        public string TelegramChannelMessage { get; set; }
        public Nullable<bool> AccessNews { get; set; }
        public Nullable<bool> AccessPagingNews { get; set; }
        public Nullable<bool> AccessGoogleSearchApi { get; set; }
        public Nullable<bool> AccessTelegram { get; set; }
        public Nullable<bool> AccessInstagram { get; set; }
        public Nullable<bool> AccessTwitter { get; set; }
        public Nullable<bool> AccessForeign { get; set; }
        public Nullable<bool> AccessTV { get; set; }
        public Nullable<bool> AccessForeignTV { get; set; }
        public Nullable<bool> AccessJaryan { get; set; }
        public Nullable<bool> AccessAnalysis { get; set; }
        public Nullable<bool> AccessDatacenter { get; set; }
        public Nullable<bool> AccessNewsFocus { get; set; }
        public Nullable<bool> AccessSearchAllMedia { get; set; }
        public Nullable<bool> AccessAdvertise { get; set; }
        public Nullable<bool> AccessEnvironmentAdvertise { get; set; }
        public Nullable<bool> AccessTvAdvertise { get; set; }
        public Nullable<bool> AccessShareOfVoice { get; set; }
        public Nullable<bool> AccessExcelExport { get; set; }
        public Nullable<bool> AllDataSendToTelegram { get; set; }
        public string AllDataTelegramChannel { get; set; }
        public Nullable<bool> SendDependOnKeyToTelegram { get; set; }
        public Nullable<bool> HasTelegramShareButton { get; set; }
        public string TelegramShareButtonChannel { get; set; }
        public Nullable<bool> SendNewsToTelegram { get; set; }
        public string SendNewsToTelegramChannel { get; set; }
        public Nullable<bool> SendMovieToTelegram { get; set; }
        public string SendMovieToTelegramChannel { get; set; }
        public Nullable<bool> SendTelegramToTelegram { get; set; }
        public string SendTelegramToTelegramChannel { get; set; }
        public Nullable<bool> SendTwitterToTelegram { get; set; }
        public string SendTwitterToTelegramChannel { get; set; }
        public Nullable<bool> SendInstagramToTelegram { get; set; }
        public string SendInstagramToTelegramChannel { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> StartDateIndex { get; set; }
        public Nullable<long> EndDateIndex { get; set; }
    
        public virtual ICollection<Tbl_InstagramKeywords> Tbl_InstagramKeywords { get; set; }
        public virtual ICollection<Tbl_InstagramPosts> Tbl_InstagramPosts { get; set; }
        public virtual ICollection<Tbl_Relation_Gallery> Tbl_Relation_Gallery { get; set; }
    }
}
