//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MediaKit_BrandArchives
    {
        public int ArchiveId { get; set; }
        public long CreateDateIndex { get; set; }
        public string YearMonthIndex { get; set; }
        public string ReportSubject { get; set; }
        public byte MediaType { get; set; }
        public string SelectedBrands { get; set; }
    }
}
