
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_MediaKitAlarm
{

    public int Id { get; set; }

    public int ParminID { get; set; }

    public bool IsRead { get; set; }

    public System.DateTime DateInsert { get; set; }

    public string Body { get; set; }

    public string Title { get; set; }

    public Nullable<System.DateTime> DateRead { get; set; }

    public int Status { get; set; }

}

}
