
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_MasterNewsTag
{

    public int ID { get; set; }

    public int ParminID { get; set; }

    public string Title { get; set; }

    public bool Active { get; set; }

    public string RssKeywordIDs { get; set; }

    public string Color { get; set; }

    public Nullable<int> OrderNumber { get; set; }

}

}
