//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TwitterPost
    {
        public long ID { get; set; }
        public long TweetID { get; set; }
        public Nullable<long> RetweetParentID { get; set; }
        public string Text { get; set; }
        public int KeywordID { get; set; }
        public string UserName { get; set; }
        public long UserID { get; set; }
        public string UserScreenName { get; set; }
        public string UserProfileImageUrl { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public long DateTimeIndex { get; set; }
        public bool IsRetweet { get; set; }
        public string Language { get; set; }
        public string Perfix { get; set; }
        public Nullable<int> QuoteCount { get; set; }
        public Nullable<int> ReplyCount { get; set; }
        public Nullable<int> RetweetCount { get; set; }
        public Nullable<int> FavoriteCount { get; set; }
        public string Suffix { get; set; }
        public string Url { get; set; }
        public string MediaUrl { get; set; }
        public string MediaType { get; set; }
        public Nullable<long> MediaID { get; set; }
        public Nullable<long> LinkUrlCRC { get; set; }
        public Nullable<bool> SendToTelegram { get; set; }
        public Nullable<bool> SendAllInOneTelegram { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> AcountID { get; set; }
        public Nullable<int> PanelID { get; set; }
        public Nullable<bool> SendDependOnKeyTelegram { get; set; }
        public Nullable<byte> NewsValue { get; set; }
    }
}
