//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MediakitUser
    {
        public int Id { get; set; }
        public int AgenceID { get; set; }
        public int ParminID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastIP { get; set; }
        public string LastSession { get; set; }
        public bool Active { get; set; }
        public bool BudgePermission { get; set; }
        public int LogCount { get; set; }
    }
}
