
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Relation_NewsParminPanel
{

    public int RelationId { get; set; }

    public Nullable<int> NewsId { get; set; }

    public Nullable<int> ParminPanelId { get; set; }

    public Nullable<int> ParminNewsId { get; set; }

    public Nullable<long> NewsDateIndex { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> CreateUser { get; set; }

    public Nullable<int> SiteId { get; set; }

    public Nullable<int> KeywordId { get; set; }

}

}
