
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_NewsRelate
{

    public int RelateId { get; set; }

    public Nullable<int> NewsId { get; set; }

    public Nullable<int> RelateNewsId { get; set; }

    public Nullable<bool> IsReference { get; set; }

    public string NewsDateTimeIndex { get; set; }

}

}
