//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SocialMediaUser
    {
        public int SocialMediaUserID { get; set; }
        public Nullable<int> SocialCode { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string ScreenName { get; set; }
        public string Url { get; set; }
        public string PictureUrl { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> RetweetsCount { get; set; }
        public string Location { get; set; }
        public Nullable<int> FriendsCount { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> FavouritesCount { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public string Language { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
