
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Telegram_Channels
{

    public int Id { get; set; }

    public Nullable<int> Channel_Id { get; set; }

    public string Channel_Name { get; set; }

    public Nullable<int> Channel_Type { get; set; }

    public Nullable<bool> Channel_GetLogo { get; set; }

    public byte[] Channel_Logo { get; set; }

}

}
