
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Telegram_SearchKeyWords
{

    public int Id { get; set; }

    public string SearchKeyWord { get; set; }

    public Nullable<int> PeriodTime { get; set; }

    public Nullable<int> msg_offset_date { get; set; }

    public Nullable<int> msg_offset_id { get; set; }

    public string DateTimePreviousSearch { get; set; }

    public Nullable<int> DateTimePreviousSearchUnix { get; set; }

    public Nullable<int> FK_GroupId { get; set; }

    public Nullable<int> FK_ParminId { get; set; }

    public Nullable<int> KeyPriority { get; set; }

}

}
