
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Tablet_Device
{

    public int DeviceID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string UUID { get; set; }

    public string AndroidVersion { get; set; }

    public string IOSVersion { get; set; }

    public string Mobile { get; set; }

    public Nullable<double> LastLocationLat { get; set; }

    public Nullable<double> LastLocationLongLat { get; set; }

}

}
