
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_InstagramKeywords
{

    public Tbl_InstagramKeywords()
    {

        this.Tbl_InstagramPosts = new HashSet<Tbl_InstagramPosts>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public int LastSearchTimeUnix { get; set; }

    public int PanelId { get; set; }

    public Nullable<int> KeysGroupID { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public Nullable<int> Priority { get; set; }

    public Nullable<System.DateTime> EditDateTime { get; set; }

    public Nullable<bool> Active { get; set; }

    public string MagnetKeywordChanel { get; set; }

    public Nullable<int> Type { get; set; }



    public virtual Tbl_NewsGroup Tbl_NewsGroup { get; set; }

    public virtual ICollection<Tbl_InstagramPosts> Tbl_InstagramPosts { get; set; }

    public virtual Tbl_Parmin Tbl_Parmin { get; set; }

}

}
