//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BultanHistory
    {
        public int ID { get; set; }
        public Nullable<int> BultanID { get; set; }
        public Nullable<System.DateTime> BultanDate { get; set; }
        public string NewsIds { get; set; }
        public string ExportPath { get; set; }
        public string fileSize { get; set; }
    }
}
