
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_GoogleSEApiNews
{

    public long Id { get; set; }

    public string Title { get; set; }

    public string Snippet { get; set; }

    public string Link { get; set; }

    public string DisplayLink { get; set; }

    public int KeywordID { get; set; }

    public int PanelId { get; set; }

    public string ImageUrl { get; set; }

    public string DateTimeString { get; set; }

    public string SiteTitle { get; set; }

    public long DateTimeIndex { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public long CRCLink { get; set; }

}

}
