
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_ProcessWork
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Comment { get; set; }

    public string FromDate { get; set; }

    public string ToDate { get; set; }

    public Nullable<int> Days { get; set; }

    public Nullable<int> Status { get; set; }

    public string EndDate { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<bool> Active { get; set; }

}

}
