//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TelegramMediaKeys
    {
        public int TelegramKeyId { get; set; }
        public int ParminID_FK { get; set; }
        public string Title { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Active { get; set; }
        public int GroupId_FK { get; set; }
        public string NotLike { get; set; }
    }
}
