//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BultanArchive
    {
        public int ArchiveId { get; set; }
        public Nullable<long> NewsDateIndex { get; set; }
        public Nullable<int> PanelId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string SelectedNews { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> AllowNewspaper { get; set; }
        public Nullable<bool> AllowGalleryNewspaper { get; set; }
        public Nullable<bool> AllowChart { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<bool> AllowHighlight { get; set; }
        public Nullable<bool> AllowRelated { get; set; }
        public Nullable<int> SelectedBultan { get; set; }
        public string FromDateIndex { get; set; }
        public string ToDateIndex { get; set; }
        public string FromTimeIndex { get; set; }
        public string ToTimeIndex { get; set; }
        public Nullable<bool> AllowJeld { get; set; }
        public Nullable<bool> AllowGroup { get; set; }
        public Nullable<bool> AllowArz { get; set; }
        public Nullable<bool> AllowSima { get; set; }
        public Nullable<byte> BultanType { get; set; }
    }
}
