
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_ExportExcelKeywords
{

    public int Id { get; set; }

    public int Type { get; set; }

    public int PanelId { get; set; }

    public bool Active { get; set; }

    public string Title { get; set; }

    public string NoWordOf { get; set; }

    public Nullable<int> KeyPriority { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public System.DateTime EditDateTime { get; set; }

}

}
