
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_MediaKit_Brands
{

    public int Id { get; set; }

    public string Brand { get; set; }

    public string LatinBrand { get; set; }

    public Nullable<int> Fk_ParentId_MediakitGroupId { get; set; }

    public Nullable<int> Fk_BrandChildId { get; set; }

    public Nullable<byte> BrandLocalType { get; set; }

}

}
