//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Highlight
    {
        public int HighlightId { get; set; }
        public Nullable<int> ParminId { get; set; }
        public Nullable<int> NewsId { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> KeywordId { get; set; }
    }
}
