
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Agences
{

    public Tbl_Agences()
    {

        this.Tbl_AgenceMembers = new HashSet<Tbl_AgenceMembers>();

        this.Tbl_Comments = new HashSet<Tbl_Comments>();

        this.Tbl_Rate = new HashSet<Tbl_Rate>();

        this.Tbl_Relation_AgenceDistrict = new HashSet<Tbl_Relation_AgenceDistrict>();

        this.Tbl_VisitHistory = new HashSet<Tbl_VisitHistory>();

    }


    public int AgenceID { get; set; }

    public Nullable<int> ViewCount { get; set; }

    public Nullable<System.Guid> AgenceGUID { get; set; }

    public string AgenceTitle { get; set; }

    public string Address { get; set; }

    public string AgenceServicePass { get; set; }

    public Nullable<System.DateTime> SignupDate { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<short> AgenceType { get; set; }

    public string District { get; set; }

    public Nullable<int> SMSCredit { get; set; }



    public virtual ICollection<Tbl_AgenceMembers> Tbl_AgenceMembers { get; set; }

    public virtual ICollection<Tbl_Comments> Tbl_Comments { get; set; }

    public virtual Tbl_CreaditHistory Tbl_CreaditHistory { get; set; }

    public virtual ICollection<Tbl_Rate> Tbl_Rate { get; set; }

    public virtual ICollection<Tbl_Relation_AgenceDistrict> Tbl_Relation_AgenceDistrict { get; set; }

    public virtual ICollection<Tbl_VisitHistory> Tbl_VisitHistory { get; set; }

}

}
