
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_TLPKeywords
{

    public int ID { get; set; }

    public string Title { get; set; }

    public string LastSearchTime { get; set; }

    public Nullable<int> LastSearchTimeUnix { get; set; }

    public Nullable<int> LastOffsetId { get; set; }

    public int ParminId { get; set; }

    public Nullable<int> KeysGroupID { get; set; }

    public Nullable<int> Priority { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.DateTime> EditDateTime { get; set; }

    public Nullable<bool> Active { get; set; }

    public string MagnetKeywordChanel { get; set; }

    public Nullable<int> Type { get; set; }

}

}
