//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TelegramSearchChannels
    {
        public int TelegramChannelID { get; set; }
        public Nullable<int> PanelID { get; set; }
        public string ChannelName { get; set; }
        public Nullable<long> ChannelID { get; set; }
        public string ChannelLink { get; set; }
        public byte[] ChannelPicture { get; set; }
    }
}
