//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tabaghat
    {
        public int TabagheId { get; set; }
        public Nullable<int> TabagheIndex { get; set; }
        public Nullable<int> TabagheYear { get; set; }
        public Nullable<long> TabaghePrice { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
