
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_TopicUsers
{

    public int ID { get; set; }

    public Nullable<int> TopicID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<System.DateTime> ViewDate { get; set; }

    public Nullable<int> ViewCount { get; set; }



    public virtual Tbl_AgenceMembers Tbl_AgenceMembers { get; set; }

}

}
