
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Online
{

    public int OnlineId { get; set; }

    public Nullable<int> CreateUser { get; set; }

    public Nullable<int> DDate { get; set; }

    public Nullable<int> SourceType { get; set; }

    public Nullable<int> PanelId { get; set; }

    public Nullable<int> SiteId { get; set; }

    public Nullable<int> Rotation { get; set; }

    public Nullable<int> Periority { get; set; }

    public Nullable<int> Position { get; set; }

    public string SourceName { get; set; }

    public Nullable<bool> PageStatus { get; set; }

    public Nullable<long> Price { get; set; }

    public string ImagePath { get; set; }

    public string Title { get; set; }

    public int PostLike { get; set; }

    public Nullable<int> PostDisLike { get; set; }

    public int PostComment { get; set; }

    public int PostView { get; set; }

    public Nullable<int> CampainId { get; set; }

    public Nullable<bool> Active { get; set; }

    public byte[] Image { get; set; }

    public Nullable<bool> IsVisible { get; set; }

}

}
