//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ads
    {
        public int AdsID { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public Nullable<int> Click { get; set; }
        public string Url { get; set; }
        public string File { get; set; }
        public string Title { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
