//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_VisitHistory
    {
        public int VisitID { get; set; }
        public Nullable<System.DateTime> VisitTime { get; set; }
        public string IP { get; set; }
        public string PageAddress { get; set; }
        public string PreviousPage { get; set; }
        public Nullable<int> AgenceID { get; set; }
    
        public virtual Tbl_Agences Tbl_Agences { get; set; }
    }
}
