
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_GoogleSEApiAccounts
{

    public int Id { get; set; }

    public string ApiKey { get; set; }

    public string cx { get; set; }

    public string SearchEnginName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string EmailAccountPhoneNumber { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<bool> suspended { get; set; }

    public Nullable<int> LastRequestTimeUnix { get; set; }

}

}
