
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Users
{

    public Tbl_Users()
    {

        this.Tbl_Events = new HashSet<Tbl_Events>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<bool> Active { get; set; }

    public string Name { get; set; }

    public string Tels { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public Nullable<byte> Type { get; set; }

    public string Permission { get; set; }



    public virtual ICollection<Tbl_Events> Tbl_Events { get; set; }

}

}
