
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_RssKeywords
{

    public int KeyId { get; set; }

    public string KeywordName { get; set; }

    public Nullable<int> PanelId { get; set; }

    public Nullable<bool> IsConfirmingKeyword { get; set; }

    public Nullable<bool> Active { get; set; }

    public string Color { get; set; }

    public Nullable<int> OrderItem { get; set; }

    public Nullable<int> GroupOrder { get; set; }

    public string GroupName { get; set; }

    public string NotLike { get; set; }

    public string ColorBg { get; set; }

    public string ColorTitle1 { get; set; }

    public string ColorTitle2 { get; set; }

    public string Mobiles { get; set; }

    public Nullable<bool> IsMobile { get; set; }

    public string KeywordImage { get; set; }

    public Nullable<bool> IsMobileNotification { get; set; }

    public Nullable<bool> IsMobileSMS { get; set; }

    public Nullable<bool> IsTelegramChannel { get; set; }

    public string TelegramChannel { get; set; }

    public Nullable<bool> IsSpecial { get; set; }

    public string MagnetKeywordChanel { get; set; }

    public Nullable<int> Type { get; set; }

}

}
