
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_CurrencyStats
{

    public int CurrencyStatsId { get; set; }

    public string Title { get; set; }

    public string LastUpdateDateTimeIndex { get; set; }

    public string DateIndex { get; set; }

    public string Price { get; set; }

    public string Diffrence { get; set; }

    public Nullable<byte> CurrencyType { get; set; }

}

}
