//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tickets
    {
        public int TicketId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Periority { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
