//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MediaKit_Groups
    {
        public int GroupId { get; set; }
        public Nullable<int> MasterParentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string GroupName { get; set; }
        public string Detail { get; set; }
        public string EnGroupName { get; set; }
    }
}
