
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_DownloadHistory
{

    public int DownloadID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> CreateUser { get; set; }

    public Nullable<bool> IsDownload { get; set; }

    public string DownloadPath { get; set; }

}

}
