
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Relation_Gallery
{

    public int RelationId { get; set; }

    public int ParminId { get; set; }

    public int ImageID { get; set; }



    public virtual Tbl_Gallery Tbl_Gallery { get; set; }

    public virtual Tbl_Parmin Tbl_Parmin { get; set; }

}

}
