//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TelegramSearchPanel
    {
        public int PanelID { get; set; }
        public string Title { get; set; }
        public string BotToken { get; set; }
        public string BotName { get; set; }
        public Nullable<long> LastTelegramIDCheck { get; set; }
    }
}
