
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Log_News
{

    public int LogId { get; set; }

    public Nullable<int> NewsId { get; set; }

    public string NewsTitle { get; set; }

    public string NewsLead { get; set; }

    public string NewsBody { get; set; }

    public string NewsDateTimeIndex { get; set; }

    public string NewsLink { get; set; }

    public string NewsPicture { get; set; }

    public string UserName { get; set; }

    public string IP { get; set; }

    public string UpdateDate { get; set; }

    public Nullable<int> ParminId { get; set; }

}

}
