//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NewsGroup
    {
        public Tbl_NewsGroup()
        {
            this.Tbl_InstagramKeywords = new HashSet<Tbl_InstagramKeywords>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ParminId { get; set; }
        public string Color { get; set; }
        public Nullable<byte> GroupType { get; set; }
        public Nullable<int> GroupOrder { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Tbl_InstagramKeywords> Tbl_InstagramKeywords { get; set; }
    }
}
