
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_TimeLineReportArchives
{

    public int ArchiveId { get; set; }

    public int PanelId { get; set; }

    public string ArchiveDateIndex { get; set; }

    public string FromDateTimeIndex { get; set; }

    public string ToDateTimeIndex { get; set; }

    public string Title { get; set; }

    public string SelectedNews { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public bool IsCover { get; set; }

    public bool IsAboutPayesh { get; set; }

    public bool IsAboutProject { get; set; }

    public bool IsFehrest { get; set; }

    public bool IsProjectSubject { get; set; }

    public byte ReportType { get; set; }

    public string CreateUser { get; set; }

    public string AboutProject { get; set; }

    public string ProjectSubject { get; set; }

    public Nullable<int> BultanFileId { get; set; }

}

}
