//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tablet_Alarm
    {
        public int AlarmID { get; set; }
        public Nullable<int> DeviceID_FK { get; set; }
        public Nullable<int> ParminID_FK { get; set; }
        public Nullable<int> NewsID_FK { get; set; }
        public Nullable<int> MovieID_FK { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AlarmType { get; set; }
        public string AlarmText { get; set; }
        public Nullable<bool> IsSent { get; set; }
    }
}
