//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sites
    {
        public Tbl_Sites()
        {
            this.Tbl_Jarayed = new HashSet<Tbl_Jarayed>();
            this.Tbl_Rss = new HashSet<Tbl_Rss>();
        }
    
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public string SiteTitle { get; set; }
        public Nullable<int> SiteType { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ParminID { get; set; }
        public Nullable<int> PanelCategory { get; set; }
        public Nullable<bool> IsPayesh { get; set; }
        public string ErrorLinks { get; set; }
        public Nullable<long> Interval { get; set; }
        public string SiteUrl { get; set; }
        public Nullable<bool> IsFeeder { get; set; }
        public string GolrangCode { get; set; }
        public Nullable<int> SitePriority { get; set; }
        public Nullable<int> SiteGroupID { get; set; }
    
        public virtual ICollection<Tbl_Jarayed> Tbl_Jarayed { get; set; }
        public virtual ICollection<Tbl_Rss> Tbl_Rss { get; set; }
    }
}
