//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_District
    {
        public Tbl_District()
        {
            this.Tbl_Relation_AgenceDistrict = new HashSet<Tbl_Relation_AgenceDistrict>();
            this.Tbl_Relation_MovieDistrict = new HashSet<Tbl_Relation_MovieDistrict>();
            this.Tbl_Relation_RadioDistrict = new HashSet<Tbl_Relation_RadioDistrict>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsAlternative { get; set; }
        public Nullable<bool> Active { get; set; }
        public string logo { get; set; }
    
        public virtual Tbl_District Tbl_District1 { get; set; }
        public virtual Tbl_District Tbl_District2 { get; set; }
        public virtual ICollection<Tbl_Relation_AgenceDistrict> Tbl_Relation_AgenceDistrict { get; set; }
        public virtual ICollection<Tbl_Relation_MovieDistrict> Tbl_Relation_MovieDistrict { get; set; }
        public virtual ICollection<Tbl_Relation_RadioDistrict> Tbl_Relation_RadioDistrict { get; set; }
    }
}
