//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Radio
    {
        public Tbl_Radio()
        {
            this.Tbl_Relation_RadioDistrict = new HashSet<Tbl_Relation_RadioDistrict>();
        }
    
        public int SoundID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Source { get; set; }
        public string SourcePath { get; set; }
        public string DDate { get; set; }
        public string TTime { get; set; }
        public string Title { get; set; }
        public string SourceLength { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Tabaghe { get; set; }
        public Nullable<int> Periority { get; set; }
        public Nullable<int> weekdayindex { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<long> DefaultPrice { get; set; }
        public Nullable<long> VideoPriceGroup { get; set; }
        public Nullable<int> Position { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> CampainId { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> CompanyType { get; set; }
        public Nullable<int> MediaKitGroupID { get; set; }
        public string SoundDateIndex { get; set; }
        public Nullable<int> NetworkGroupID { get; set; }
        public string PosterPath { get; set; }
    
        public virtual ICollection<Tbl_Relation_RadioDistrict> Tbl_Relation_RadioDistrict { get; set; }
    }
}
