//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bilboards
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public Nullable<double> LastLatitude { get; set; }
        public Nullable<double> LastLongitude { get; set; }
        public string District { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public string Zone { get; set; }
        public string Company { get; set; }
        public string City { get; set; }
        public Nullable<int> LocationZone { get; set; }
        public Nullable<int> LocationType { get; set; }
    }
}
