
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_PhoneBook
{

    public int PersonID { get; set; }

    public string PersonGroup { get; set; }

    public string PersonName { get; set; }

    public string Tel { get; set; }

    public string Fax { get; set; }

    public string Website { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public Nullable<int> Sex { get; set; }

    public string Address { get; set; }

}

}
