
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_InstagramPosts
{

    public long Id { get; set; }

    public long InstagramPostId { get; set; }

    public string TypeName { get; set; }

    public string ShortCode { get; set; }

    public string DisplayUrl { get; set; }

    public Nullable<bool> IsVideo { get; set; }

    public string CaptionText { get; set; }

    public Nullable<int> LikeCount { get; set; }

    public Nullable<int> CommentsCount { get; set; }

    public System.DateTime DateTime { get; set; }

    public long DateTimeIndex { get; set; }

    public System.DateTime ReadDateTime { get; set; }

    public string VideoUrl { get; set; }

    public int KeywordId { get; set; }

    public Nullable<bool> SendAllInOneTelegram { get; set; }

    public Nullable<bool> SendDependOnKeyTelegram { get; set; }

    public Nullable<bool> Active { get; set; }

    public string PostUrl { get; set; }

    public long UserId { get; set; }

    public string ProfilePicUrl { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public Nullable<bool> UserIsVerified { get; set; }

    public int PanelId { get; set; }

    public Nullable<byte> NewsValue { get; set; }



    public virtual Tbl_InstagramKeywords Tbl_InstagramKeywords { get; set; }

    public virtual Tbl_Parmin Tbl_Parmin { get; set; }

}

}
