
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Attachments
{

    public int AttachID { get; set; }

    public Nullable<short> FileType { get; set; }

    public string Title { get; set; }

    public Nullable<int> ViewCount { get; set; }

    public string SourceFile { get; set; }

    public Nullable<int> TopicID { get; set; }

    public Nullable<long> FileSize { get; set; }



    public virtual Tbl_Topics Tbl_Topics { get; set; }

}

}
