//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SocialMediaBultanPost
    {
        public int SocialMediaBultanPostID { get; set; }
        public Nullable<int> SocialMediaBultanID_FK { get; set; }
        public Nullable<int> SocialMediaPostID_FK { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser_FK { get; set; }
    }
}
