
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace P_Art.Pages.P_Art.ModelNews
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Keywords
{

    public Tbl_Keywords()
    {

        this.Tbl_KeywordEvents = new HashSet<Tbl_KeywordEvents>();

    }


    public int id { get; set; }

    public string KeyName { get; set; }

    public Nullable<int> ParminId { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public Nullable<int> Type { get; set; }

    public Nullable<bool> IsParent { get; set; }

    public string SecondKey { get; set; }

    public string ColorBg { get; set; }

    public string ColorTitle1 { get; set; }

    public string ColorTitle2 { get; set; }



    public virtual ICollection<Tbl_KeywordEvents> Tbl_KeywordEvents { get; set; }

}

}
