//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Art.Pages.P_Art.ModelNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TLP_Messages
    {
        public long ID { get; set; }
        public Nullable<int> PostID { get; set; }
        public int KeywordID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string MessageText { get; set; }
        public string MessageDate { get; set; }
        public string MessageTime { get; set; }
        public Nullable<long> DateTimeIndex { get; set; }
        public Nullable<System.DateTime> CreateDateTIme { get; set; }
        public int PanelID { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<bool> ShowStatus { get; set; }
        public Nullable<int> MediaType { get; set; }
        public Nullable<long> MediaID { get; set; }
        public Nullable<byte> SentToTelegram { get; set; }
        public Nullable<bool> SendAllInOneTelegram { get; set; }
        public Nullable<bool> SendDependOnKeyTelegram { get; set; }
        public Nullable<byte> NewsValue { get; set; }
        public string Title { get; set; }
        public string ChannelTitle { get; set; }
        public string Username { get; set; }
    }
}
